parameters:
    ped_discriminator_map.listener.class: PaneeDesign\DiscriminatorMapBundle\EventListener\DiscriminatorMapListener
    ped_discriminator_map.maps: ''

services:
    ped_discriminator_map.listener:
        class: "%ped_discriminator_map.listener.class%"
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }
        arguments: ['%ped_discriminator_map.maps%']
        public: true