parameters:
    ped_discriminator.listener.class: PaneeDesign\DiscriminatorMapBundle\EventListener\DiscriminatorMapListener
    ped_discriminator.map: ''

services:
    ped_discriminator.listener:
        class: "%ped_discriminator.listener.class%"
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }
        arguments: ['%ped_discriminator.map%']
        public: true